version: '3'

services:

#  engine:
#    build:
#      context: docker
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./:/var/app/

  gcc:
    build:
      context: docker/gcc
#    stdin_open: true
#    tty: true
    volumes:
      - ./:/var/app/
